apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:8.0.18
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_USER
        value: admin
      - name: MYSQL_PASSWORD
        value: password
      - name: MYSQL_HOST
        value: "0.0.0.0"
      - name: MYSQL_PORT
        value: "8080"
      - name: MYSQL_DATABASE
        value: internship
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}