apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: instabugger
  name: instabugger
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: instabugger
  type: NodePort
status:
  loadBalancer: {}